"""
Django settings for cmtbackend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import config
from rest_framework.settings import api_settings
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "rest_framework_swagger",
    "drf_yasg",
    "storages",
    "documents",
    "rest_framework",
    "corsheaders",
    "bankmanagement",
    "django_otp.plugins.otp_totp",
    "knox",
    "payment",
    "django_filters",
    "filemanagement",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "cmtbackend.custom_middleware_validation.NotFoundMiddleware",
    "cmtbackend.token_verification_middleware.TokenVerificationMiddleware",
    "cmtbackend.custom_middleware_validation.SpecialCharacterMiddleware",
    "cmtbackend.custom_middleware_validation.DecodeURLEncodedMiddleware",
    "cmtbackend.custom_middleware_validation.CustomMiddleware",
]

ROOT_URLCONF = "cmtbackend.urls"

# Secure cookies over HTTPS only
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Prevent JavaScript access
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

AUTH_USER_MODEL = "users.Users"

WSGI_APPLICATION = "cmtbackend.wsgi.application"

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_NOTIFICATION_RECIPIENTS = [
    email.strip()
    for email in config("EMAIL_NOTIFICATION_RECIPIENTS").split(",")
    if email.strip()
]
EMAIL_USE_TLS = True
EMAIL_PORT = 587
# DEFAULT_FROM_EMAIL = 'default from email'
EMAIL_USE_SSL = False
SMTP_USERNAME = config("SMTP_USERNAME")
SMTP_PASSWORD = config("SMTP_PASSWORD")

LEGACY_DOCUMENTS_BUCKET = config("LEGACY_DOCUMENTS_BUCKET")
DOCUMENTS_UPLOAD_BUCKET = config("DOCUMENTS_UPLOAD_BUCKET")

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": config("DATABASE_NAME"),
        "USER": config("DATABASE_USER"),
        "PASSWORD": config("DATABASE_PASSWORD"),
        "HOST": config("DATABASE_HOST"),
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

USE_S3 = True
# USE_S3 = False

if USE_S3:
    # aws Media settings...
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_CUSTOM_DOMAIN = "%s.s3.amazonaws.com" % AWS_STORAGE_BUCKET_NAME
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME")
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
    AWS_DEFAULT_ACL = None
    AWS_S3_SECURE_URLS = False
    DEFAULT_FILE_STORAGE = "cmtbackend.storage_backends.MediaStorage"

    # Static Root settings..
    # AWS_LOCATION = 'static'
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)

else:
    pass
    # STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    # MEDIA_URL = '/media/'
    # MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    # print(MEDIA_ROOT,"DDDDDDDDDDDDD")

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_HEADERS = list(default_headers) + [
    'login-method',
    'user-id',
    'referer'
]


REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": ("knox.auth.TokenAuthentication",),
}

REST_KNOX = {
    "SECURE_HASH_ALGORITHM": "cryptography.hazmat.primitives.hashes.SHA512",
    "AUTH_TOKEN_CHARACTER_LENGTH": 64,
    "TOKEN_TTL": timedelta(minutes=60),
    "USER_SERIALIZER": "knox.serializers.UserSerializer",
    "TOKEN_LIMIT_PER_USER": None,
    "AUTO_REFRESH": True,
    "EXPIRY_DATETIME_FORMAT": api_settings.DATETIME_FORMAT,
}

# CORS ALLOWED ORIGINS
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = (
    config("ALLOWED_ORIGINS").split(",") if config("ALLOWED_ORIGINS") else []
)
CSRF_TRUSTED_ORIGINS = (
    config("ALLOWED_ORIGINS").split(",") if config("ALLOWED_ORIGINS") else []
)
ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(",") if config("ALLOWED_HOSTS") else []

# WORK FLOW
WORK_FLOW_INITIATE_BODY = """
<html>
            <head>
            </head>
            <body>
                <div class="email-body">
                    <div class="email-header">
                        <img src="{imagepath}" alt="Mosaic Insurance Logo">
                    </div>
                    <p>Dear {reviewer_approver},</p>
                    <p>A new worklist item {transaction_id} has been assigned to you, initiated by {initiator}. Please review it as soon as possible.</p>

                    <p>If you have any questions, email us at <a href="mailto:support@mosaicinsurance.com">support@mosaicinsurance.com</a>.</p>
                    <p>If you no longer wish to receive these email notifications, you can unsubscribe by replying to this email with "Unsubscribe" in the subject line.</p>

                    <div class="email-footer">
                        <p>Regards,<br>Mosaic Insurance</p>
                    </div>
                    <p>This message, including any attachments, may include proprietary or confidential material. Any distribution or use of this communication by anyone other than the intended recipient(s) is prohibited. If you are not the intended recipient, please notify the sender by replying to this message and then deleting it from your system.</p>
                </div>
            </body>
        </html>
"""

WORK_FLOW_CHANGE_STATUS_BODY = """
<html>
            <head>
            </head>
            <body>
                <div class="email-body">
                    <div class="email-header">
                        <img src="{imagepath}" alt="Mosaic Insurance Logo">
                    </div>
                    <p>Dear {initiator},,</p>
                    <p>The worklist item {transaction_id} initiated by you has been {status} by {reviewer_approver}.</p>

                    <p>If you have any questions, email us at <a href="mailto:support@mosaicinsurance.com">support@mosaicinsurance.com</a>.</p>
                    <p>If you no longer wish to receive these email notifications, you can unsubscribe by replying to this email with "Unsubscribe" in the subject line.</p>

                    <div class="email-footer">
                        <p>Regards,<br>Mosaic Insurance</p>
                    </div>
                    <p>This message, including any attachments, may include proprietary or confidential material. Any distribution or use of this communication by anyone other than the intended recipient(s) is prohibited. If you are not the intended recipient, please notify the sender by replying to this message and then deleting it from your system.</p>
                </div>
            </body>
        </html>
"""

WORK_FLOW_CHANGE_STATUS_REVIEWER_BODY = """
<html>
            <head>
            </head>
            <body>
                <div class="email-body">
                    <div class="email-header">
                        <img src="{imagepath}" alt="Mosaic Insurance Logo">
                    </div>
                    <p>Dear {reviewer_approver},</p>
                    <p>A new worklist item {transaction_id} has been assigned to you, initiated by {initiator}. Please review it as soon as possible.</p>

                    <p>If you have any questions, email us at <a href="mailto:support@mosaicinsurance.com">support@mosaicinsurance.com</a>.</p>
                    <p>If you no longer wish to receive these email notifications, you can unsubscribe by replying to this email with "Unsubscribe" in the subject line.</p>

                    <div class="email-footer">
                        <p>Regards,<br>Mosaic Insurance</p>
                    </div>
                    <p>This message, including any attachments, may include proprietary or confidential material. Any distribution or use of this communication by anyone other than the intended recipient(s) is prohibited. If you are not the intended recipient, please notify the sender by replying to this message and then deleting it from your system.</p>
                </div>
            </body>
        </html>
"""

WORK_FLOW_CHANGE_STATUS_CONFIRMATION_BODY = """
<html>
            <head>
            </head>
            <body>
                <div class="email-body">
                    <div class="email-header">
                        <img src="{imagepath}" alt="Mosaic Insurance Logo">
                    </div>
                    <p>Dear {reviewer_approver},</p>
                    <p>Status of {transaction_id} is changed. No further action from your end is required.</p>

                    <p>If you have any questions, email us at <a href="mailto:support@mosaicinsurance.com">support@mosaicinsurance.com</a>.</p>
                    <p>If you no longer wish to receive these email notifications, you can unsubscribe by replying to this email with "Unsubscribe" in the subject line.</p>

                    <div class="email-footer">
                        <p>Regards,<br>Mosaic Insurance</p>
                    </div>
                    <p>This message, including any attachments, may include proprietary or confidential material. Any distribution or use of this communication by anyone other than the intended recipient(s) is prohibited. If you are not the intended recipient, please notify the sender by replying to this message and then deleting it from your system.</p>
                </div>
            </body>
        </html>
"""

USER_ONBOARD = """
<html>
                <head>
                </head>
                <body>
                    <div class="email-body">
                        <div class="email-header">
                            <img src="{imagepath}" alt="Mosaic Insurance Logo">
                        </div>
                        <p>Dear User,</p>
                        <p>Welcome to Mosaic Insurance! We are delighted to have you on board.</p>
                        <p>Your one-time password: <strong>{password}</strong></p>
                        <p>If you have any questions, email us at <a href="mailto:support@mosaicinsurance.com">support@mosaicinsurance.com</a>.</p>
                        <div class="email-footer">
                            <p>Regards,<br>Mosaic Insurance</p>
                        </div>
                    </div>
                </body>
            </html>
"""

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": config("LOG_FILE_PATH"),
        },
    },
    "root": {
        "handlers": ["file"],
        "level": "DEBUG",  # Global capture
    }
}

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'  # URL for Redis broker
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'  # URL for Redis result backend
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
