from django.db import models
import json

# Create your models here.

from users.models import *
from documents.models import *
from datetime import datetime


class WorkStep(models.Model):
    step_name = models.CharField(max_length=200)
    comments = models.TextField(blank=True, null=True)
    user = models.ManyToManyField(Users, blank=True, related_name="workstep_users")
    ctime = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    uptime = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=100, blank=True, null=True)
    step_seq_no = models.IntegerField(null=True)
    step_process = models.CharField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        ordering = ('step_seq_no',)


class WorkFlow(models.Model):
    workflow_name = models.CharField(max_length=200)
    workflow_step = models.ManyToManyField(WorkStep, blank=True, related_name="worksteps")
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class BankReconciliation(models.Model):
    bank_account_no = models.CharField(max_length=100, null=True)
    file_name = models.CharField(max_length=100, null=True)
    uploaded_date = models.DateField()
    uploaded_time = models.DateTimeField()
    file_date = models.DateField()
    uploaded_status = models.CharField(max_length=100, null=True)
    credit_amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    debit_amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    total_amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    ct_amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    ct_receivable_amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    ct_amount_car = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    ct_receivable_amount_var = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    bank_charges = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    ct_bank_charges = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    ct_bank_charges_var = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    category_total = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    error_message = models.TextField(null=True, max_length=500)
    locked = models.BooleanField(null=True, default=False)
    allocated_analyst_id = models.ForeignKey(Users, on_delete=models.SET_NULL, null=True, blank=True, related_name="allocated_analyst_id")
    allocated_date = models.DateField()
    final_status = models.CharField(max_length=100, null=True)
    analyst_comments = models.TextField(null=True)
    resolution_date = models.DateField()
    file_name_hyperlink = models.TextField(null=True)
    # add bank_id (1st may)
    bank_details = models.ForeignKey(BankDetails, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=200, blank=True, null=True)
    migrated_data = models.IntegerField(null=True)
    auto_created = models.IntegerField(null=True)
    ct_category = models.CharField(max_length=200, null=True)
    ct_comments = models.CharField(max_length=500, null=True)
    ct_calculated_amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    uploaded_by = models.ForeignKey(Users, on_delete=models.SET_NULL, null=True, blank=True, related_name="uploaded_by")


class BankTransaction(models.Model):
    Bank_Transaction_Id = models.CharField(max_length=100)
    Accounting_Month = models.DateField()
    PT_Receving_Bank_Name = models.CharField(max_length=100)
    Bank_Account_Name_Entity = models.CharField(max_length=100)
    Receiving_Bank_Account = models.CharField(max_length=100, blank=True, null=True)
    Broker_Branch = models.CharField(max_length=250)
    Broker = models.CharField(max_length=250)
    Payment_Receive_Date = models.DateTimeField()
    Payment_Reference = models.TextField(null=True)
    Payment_Currency_Code = models.CharField(max_length=100)
    Bank_Currency_Code = models.CharField(max_length=100)
    Bank_Exchange_Rate = models.DecimalField(decimal_places=6, max_digits=14, null=True)
    Bank_Exchange_Charges = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    Bank_Charges = models.DecimalField(decimal_places=4, max_digits=14, null=True)
    Receivable_Amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    Receivable_Amount_USD = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    TL_Fees = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    Currency = models.CharField(max_length=100)
    File_Name = models.FileField(upload_to='bank/media/', blank=True, null=True)
    Created_By = models.CharField(max_length=100)
    Analyst_Name = models.CharField(max_length=100)
    Date_And_Time = models.DateTimeField(max_length=100)
    Uploaded_By = models.CharField(max_length=100)
    Assigned_User = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, blank=True)
    Assigned_Users = models.ManyToManyField(Users, blank=True, related_name="users")
    assigned_users_list = models.CharField(max_length=50000, blank=True, null=True)
    Allocation_Status = models.CharField(max_length=100, null=True)
    workflow = models.ForeignKey(WorkFlow, on_delete=models.CASCADE, null=True, blank=True)
    document_files = models.ManyToManyField(Documents, blank=True, related_name="documents")
    broker_information = models.ForeignKey(BrokerInformation, on_delete=models.CASCADE, null=True, blank=True)
    bank_details = models.ForeignKey(BankDetails, on_delete=models.CASCADE, null=True, blank=True)
    updated_by = models.CharField(max_length=100, null=True, blank=True)
    updatedDateAndTime = models.DateTimeField(null=True, blank=True)
    updated_fields = models.TextField(null=True, blank=True)
    bank_reconciliation = models.ForeignKey(BankReconciliation, on_delete=models.CASCADE, null=True, blank=True)
    auto_upload = models.BooleanField(default=True)
    locked = models.BooleanField(null=True, default=False)
    error = models.CharField(max_length=200, blank=True, null=True)
    txn_category = models.CharField(max_length=200, blank=True, null=True)
    assigned_date = models.DateField(max_length=100, null=True)
    batch_ref = models.CharField(max_length=100, null=True)
    comment = models.TextField(null=True)
    transaction_status = models.CharField(max_length=200, null=True, default="Open")                     # CMT-28
    Aging_Bucket = models.CharField(max_length=100, null=True)
    ROE = models.DecimalField(decimal_places=6, max_digits=14, null=True)
    ROE_Date = models.DateField(null=True)
    correction_type = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    archived = models.BooleanField(default=False)
    txn_type = models.CharField(max_length=10, blank=True, null=True)

    def set_assigned_users_list(self, x):
        self.assigned_users_list = json.dumps(x)

    def get_assigned_users_list(self):
        if self.assigned_users_list is None:
            return None
        return json.loads(self.assigned_users_list)
    
    def get_txn_type(self):
        if self.Receivable_Amount is not None:
            if float(self.Receivable_Amount) < 0:
                self.txn_type = 'Outflow'
            else:
                self.txn_type = 'Inflow'
        return self.txn_type

    def save(self, *args, **kwargs):
        # Automatically set txn_type before saving
        if not self.txn_type:
            self.txn_type = self.get_txn_type()  # Call the method to determine txn_type
        super().save(*args, **kwargs)  # Call the original save method


class CashAllocation(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE)
    bank_reconciliation_id = models.IntegerField(null=True)
    allocation_status = models.CharField(max_length=100, null=True)
    allocation_systemid = models.CharField(max_length=100, null=True)
    policy_id = models.CharField(max_length=100, null=True)
    allocation_entity = models.CharField(max_length=100, null=True)
    allocation_binder = models.CharField(max_length=100, null=True)
    allocation_umr = models.CharField(max_length=100, null=True)
    binding_agreement = models.CharField(max_length=100, null=True)
    allocation_eea = models.CharField(max_length=100, null=True)
    allocation_scm = models.CharField(max_length=100, null=True)
    allocation_scmname = models.CharField(max_length=100, null=True)
    allocation_invoice_verification = models.CharField(max_length=100, null=True)
    receivable_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    allocated_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    unallocated_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    XFIbatchno = models.CharField(max_length=100, null=True)
    cashreference = models.CharField(max_length=100, null=True)
    GXPbatchno = models.CharField(max_length=100, null=True)
    allocation_date = models.DateField(default=None, null=True, blank=True)
    accounting_monthyear = models.DateField(default=None, null=True)
    allocatedby = models.CharField(max_length=100, null=True)
    isActive = models.BooleanField(default=True)
    bank_roe = models.DecimalField(decimal_places=6, max_digits=12, null=True, default=1.00000)
    payment_currency = models.CharField(max_length=100, blank=True, null=True)
    bank_curr = models.CharField(max_length=100, null=True)
    cash_reference = models.CharField(max_length=100, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy")
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    locked = models.BooleanField(max_length=100, blank=True, null=True)
    locked_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True)
    locked_datetime = models.DateField(null=True)

    # historical, set it 1 when running migrations (1st may)
    historical = models.BooleanField(default=False, null=True)
    xfi_amount = models.DecimalField(decimal_places=2, max_digits=12, null=True, default=0.0)
    gxbamount = models.DecimalField(decimal_places=2, max_digits=12, default=0.0)
    xfi_variance_amount = models.DecimalField(decimal_places=2, max_digits=12, null=True, default=0.0)
    gxb_variance_amount = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    installment_number = models.IntegerField(default=0)
    installment_duedate = models.DateField(null=True)
    installment_amount_org = models.DecimalField(decimal_places=2, max_digits=12, null=True, default=0)
    settlement_ccy = models.ForeignKey(CurrencyDetails, on_delete=models.CASCADE, null=True)
    # remaining balance != 0 and today's payment_rec_date

    manual_entry = models.BooleanField(default=False, null=True)
    comment = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    created_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, related_name='created_by')
    updated_at = models.DateTimeField(auto_now=True, null=True)
    updated_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, related_name='updated_by')
    settlement_currency = models.CharField(max_length=20, null=True)
    excel_ref = models.IntegerField(null=True)
    policy_installment_number = models.IntegerField(default=0)
    original_ccy = models.CharField(max_length=20, null=True, blank=True)
    archived = models.BooleanField(default=False)

    # Contra Allocation Columns
    is_contra_allocation = models.BooleanField(default=False, null=True)
    parent_contra_id = models.IntegerField(null=True)
    child_contra_id = models.IntegerField(null=True)

    deleted_ca = models.IntegerField(null=True)
    deleted_time = models.DateTimeField(null=True)
    policy_handler = models.ForeignKey(Users, on_delete=models.SET_NULL, null=True, related_name='policy_handler')
    policy_assign_date = models.DateField(null=True, blank=True)


class CashAllocationIssues(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.SET_NULL, null=True)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.SET_NULL, null=True)
    policy_id = models.CharField(max_length=100, null=True)
    issue_category = models.CharField(max_length=100, null=True)
    issue_owner = models.CharField(max_length=100, null=True)
    correction_type = models.ForeignKey(CorrectionType, on_delete=models.SET_NULL, null=True)
    system_id = models.CharField(max_length=100, null=True)
    comments = models.CharField(null=True)
    assignment = models.CharField(max_length=150, null=True)
    issue_date = models.DateField(default=None, null=True)
    age_days = models.IntegerField(null=True, default=0)
    accounting_monthyear = models.DateField(default=None, null=True)
    isActive = models.BooleanField(default=True, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_issues", null=True)
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    correction_type_desc = models.CharField(max_length=200, null=True)
    is_auto_initiated = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)

class CashAllocationCorrective(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE, null=True)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE, null=True)
    policy_id = models.CharField(max_length=100, null=True)
    transfer_amt = models.DecimalField(decimal_places=2, max_digits=12)
    producing_entity_bankid = models.CharField(max_length=100, null=True)
    producing_bank_currid = models.CharField(max_length=100, null=True)
    bank_roe = models.DecimalField(decimal_places=6, max_digits=12, null=True)
    payment_currid = models.CharField(max_length=100, null=True)
    bank_curr = models.CharField(max_length=100, null=True)
    receivable_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    allocated_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    unallocated_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    accounting_monthyear = models.DateField(default=None, null=True)
    allocation_date = models.DateField(default=datetime.now().date(), null=True)
    request_date = models.DateField(default=datetime.now().date(), null=True)
    receiving_entity_bank_account = models.CharField(max_length=200, null=True)
    bank_account = models.CharField(max_length=200, null=True)
    currency_from_bank_stmt = models.CharField(max_length=100, null=True)
    transfer_pt_bank_account_name = models.CharField(max_length=200, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_corrective", null=True)
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    treasury_confirmed_transfer_date = models.DateField(default=None, null=True)
    PT_bank_acct_Number = models.CharField(max_length=100, null=True)
    approver_id = models.CharField(max_length=100, null=True)
    approved_status = models.CharField(max_length=10, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    is_auto_initiated = models.BooleanField(default=False)
    comments = models.CharField(max_length=100, null=True)
    archived = models.BooleanField(default=False)


class CashAllocationWriteoff(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE)
    policy_id = models.CharField(max_length=100, null=True)
    writeoff_reason = models.TextField()
    request_date = models.DateField(default=datetime.now().date(), null=True)
    writeoff_amt = models.DecimalField(decimal_places=2, max_digits=12)
    comments = models.TextField()
    approved_date = models.DateField(default=datetime.now().date(), null=True)
    aprover_name = models.CharField(max_length=100, blank=True)
    process_date = models.DateField(default=datetime.now().date(), null=True)
    system_id = models.CharField(max_length=100, null=True)
    accounting_monthyear = models.DateField(default=datetime.now().date(), null=True)
    currency = models.CharField(max_length=100, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_writeoff")
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    cash_reference = models.CharField(max_length=100, null=True)
    approver_id = models.CharField(max_length=100, null=True)
    approved_status = models.CharField(max_length=10, null=True)
    archived = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class CashAllocationRefund(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE, null=True)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE, null=True)
    policy_id = models.CharField(max_length=100, null=True)
    refund_reason = models.TextField(null=True)
    request_date = models.DateField(default=datetime.now().date(), null=True)
    refund_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    comments = models.TextField(null=True)
    approved_date = models.DateField(default=datetime.now().date(), null=True)
    aprover_name = models.CharField(max_length=100, blank=True, null=True)
    process_date = models.DateField(default=datetime.now().date(), null=True)
    system_id = models.CharField(max_length=100, null=True)
    accounting_monthyear = models.DateField(null=True)
    currency = models.CharField(max_length=100, null=True)
    bank_transaction_id = models.CharField(max_length=200, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_refund", null=True)
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    broker_name = models.CharField(max_length=100, null=True)
    approver_id = models.CharField(max_length=100, null=True)
    approved_status = models.CharField(max_length=10, null=True)
    archived = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class CashAllocationCFI(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE)
    policy_id = models.CharField(max_length=100, null=True)
    request_date = models.DateField(default=datetime.now().date(), null=True)
    cfi_amt = models.DecimalField(decimal_places=2, max_digits=12)
    cfi_change = models.CharField(max_length=100)
    cfi_impact = models.CharField(max_length=100)
    reallocation_date = models.DateField(default=None, null=True)
    approved_date = models.DateField(default=None, null=True)
    aprover_name = models.CharField(max_length=100, blank=True)
    process_date = models.DateField(default=None, null=True)
    system_id = models.CharField(max_length=100, null=True)
    accounting_monthyear = models.DateField(default=None, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_cfi")
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    approver_id = models.CharField(max_length=100, null=True)
    approved_status = models.CharField(max_length=10, null=True)
    archived = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class CrossAllocation(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE)
    policy_id = models.CharField(max_length=100, null=True)
    request_date = models.DateField(default=datetime.now().date(), null=True)
    ca_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    ca_change = models.CharField(max_length=100, null=True)
    ca_impact = models.CharField(max_length=100, null=True)
    approved_date = models.DateField(default=datetime.now().date(), null=True)
    aprover_name = models.CharField(max_length=100, blank=True)
    process_date = models.DateField(default=datetime.now().date(), null=True)
    system_id = models.CharField(max_length=100, null=True)
    accounting_monthyear = models.DateField(default=None, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_ca")
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    new_allocation_date = models.DateField(default=datetime.now().date(), null=True)
    approver_id = models.CharField(max_length=100, null=True)
    approved_status = models.CharField(max_length=10, null=True)
    archived = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class CashAllocationMSD(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE)
    policy_id = models.CharField(max_length=100, null=True)
    msd_amt = models.DecimalField(decimal_places=2, max_digits=12)
    je_number = models.CharField(max_length=100)
    comments = models.TextField()
    process_date = models.DateField(default=None, null=True)
    system_date = models.DateField(default=None, null=True)
    accounting_monthyear = models.DateField(default=None, null=True)
    user_id = models.CharField(max_length=100, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_msd")
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    approver_id = models.CharField(max_length=100, null=True)
    approved_status = models.CharField(max_length=10, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class PremiumPayment(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE)
    policy_id = models.CharField(max_length=100, null=True)
    paid_amt = models.DecimalField(decimal_places=2, max_digits=12)
    allocated_amt = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    payment_status = models.CharField(max_length=100)
    payment_date = models.DateField(default=None, null=True)
    wire_number = models.CharField(max_length=100)
    comments = models.TextField()
    system_date = models.DateField(default=None, null=True)
    user_id = models.CharField(max_length=100, null=True)
    accounting_monthyear = models.DateField(default=None, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_premium")
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class CorrectiveTRF(models.Model):
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE)
    policy_id = models.CharField(max_length=100, null=True)
    receivable_amt = models.DecimalField(decimal_places=2, max_digits=12)
    payment_status = models.CharField(max_length=100)
    payment_date = models.DateField(default=datetime.now().date(), null=True)
    wire_number = models.CharField(max_length=100)
    comments = models.TextField()
    system_date = models.DateField(default=datetime.now().date(), null=True)
    user_id = models.CharField(max_length=100, null=True)
    accounting_monthyear = models.DateField(default=None, null=True)
    policy_mf = models.ManyToManyField(PolicyInformation, blank=True, related_name="policy_trf")
    policy_fk = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class CashTracker(models.Model):
    Accounting_Monthy = models.DateField(default=None, null=True)
    Allocation_Status = models.CharField(max_length=100, null=True)
    Division = models.CharField(max_length=100, null=True)
    Receiving_Bank_Account = models.CharField(max_length=100, null=True)
    Cash_Transfers = models.CharField(max_length=100, null=True)
    Policy_Type = models.CharField(max_length=100, null=True)
    LOB = models.CharField(max_length=100, null=True)
    Broker = models.CharField(max_length=100, null=True)
    Broker_Branch = models.CharField(max_length=100, null=True)
    Binding_Agreement = models.CharField(max_length=100, null=True)
    SCM_Partners = models.CharField(max_length=100, null=True)
    EEA_Non_EEA = models.CharField(max_length=100, null=True)
    Payment_Receive_Date = models.DateField(default=None, null=True, blank=True)
    Payment_Currency_Code = models.CharField(max_length=100, null=True, blank=True)
    ROE_Bank_Statement = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    Master_Binder = models.CharField(max_length=100, null=True)
    Policy = models.CharField(max_length=100, null=True)
    Category = models.CharField(max_length=100, null=True)
    Bank_Charges = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    Receivable_Amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    Allocated_Amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    bank_name = models.CharField(max_length=100, null=True)
    txn_id = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class CashTrackerReport(models.Model):
    Accounting_Month = models.CharField(max_length=100, null=True)
    Premium_BDX = models.CharField(max_length=100, null=True)
    XIS_Transfer_Date = models.CharField(max_length=100, null=True)
    XIS_Package_no = models.CharField(max_length=100, null=True)
    MSD_Journal = models.CharField(max_length=100, null=True)
    Invoice_Verification = models.CharField(max_length=100, null=True)
    Producing_Coverholder = models.CharField(max_length=100, null=True)
    PT_Receving_Bank_Account_Name = models.CharField(max_length=100, null=True)
    Receiving_Bank_Account = models.CharField(max_length=100, null=True)
    Transfer_to_PT_Bank_Account_Name = models.CharField(max_length=100, null=True)
    Transfer_to_PT_Bank_Account = models.CharField(max_length=100, null=True)
    Treasury_Confirmed_Transfer_Date = models.CharField(max_length=100, null=True)
    Policy_Type = models.CharField(max_length=100, null=True)
    LOB = models.CharField(max_length=100, null=True)
    Broker = models.CharField(max_length=100, null=True)
    Broker_Branch = models.CharField(max_length=100, null=True)
    Third_Party_Capacity = models.CharField(max_length=100, null=True)
    Binding_Agreement = models.CharField(max_length=100, null=True)
    SCM_Partners = models.CharField(max_length=100, null=True)
    SCM_Partner_Status = models.CharField(max_length=100, null=True)
    EEA_NonEEA = models.CharField(max_length=100, null=True)
    Payment_Receive_Date = models.CharField(max_length=100, null=True, blank=True)
    Payment_Reference = models.TextField(null=True)
    Payment_Currency_Code = models.CharField(max_length=100, null=True, blank=True)
    Bank_Currency_Code = models.CharField(max_length=100, null=True, blank=True)
    ROE_Bank_Statement = models.DecimalField(decimal_places=8, max_digits=18, null=True)
    YOA = models.CharField(max_length=100, null=True)
    Master_Binder = models.CharField(max_length=100, null=True)
    Policy = models.CharField(max_length=100, null=True)
    Category = models.CharField(max_length=100, null=True)
    Payment_Special_Instructions = models.TextField(null=True)
    Currency = models.CharField(max_length=100, null=True)
    Mosaic_percent = models.DecimalField(decimal_places=6, max_digits=12, null=True)
    Coverholder_Fee_Amount = models.CharField(max_length=100, null=True)
    MGA_Commission = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Bank_Charges = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Receivable_Amount = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Allocated_Amount = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Remaining_Balance = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Total_Receivables_including_Bank_Charges = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Receivable_Amount_calculated = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Allocated_Amount_calculated = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Remaining_Balance_usd = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    Mosaic_Amount = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    MGA_Commission_calculated = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    TL_Fees = models.CharField(max_length=100, null=True)
    Bank_Charges_calculated = models.CharField(max_length=100, null=True)
    Aging_Bucket = models.CharField(max_length=100, null=True)
    Payment_Status = models.CharField(max_length=100, null=True)
    Batch = models.CharField(max_length=100, null=True)
    Cash_Reference = models.CharField(max_length=100, null=True)
    GXB_Batch = models.CharField(max_length=100, null=True)
    Account_Handler = models.CharField(max_length=100, null=True)
    XFI_Allocated_Date = models.CharField(max_length=100, null=True)
    Allocation_Status = models.CharField(max_length=100, null=True)
    System_Correction = models.CharField(max_length=100, null=True)
    Corretion_Type = models.CharField(max_length=100, null=True)
    Comment = models.CharField(max_length=100, null=True)
    Team = models.CharField(max_length=100, null=True)
    Owner = models.CharField(max_length=100, null=True)
    Initial_Query_Date = models.CharField(max_length=100, null=True)
    Escalation_Owner = models.CharField(max_length=100, null=True)
    Escalation_Date = models.CharField(max_length=100, null=True)
    GXB_Status = models.CharField(max_length=100, null=True)
    GXB_Allocation_Date = models.CharField(max_length=100, null=True)
    no_of_Days_Overdue = models.CharField(max_length=100, null=True)
    SLA = models.CharField(max_length=100, null=True)
    SLA_Compliance = models.CharField(max_length=100, null=True)
    Week = models.CharField(max_length=100, null=True)
    percent_Change = models.CharField(max_length=100, null=True)
    Payment_Receive_Week = models.CharField(max_length=100, null=True)
    Allocation_Week = models.CharField(max_length=100, null=True)
    Reporting_Week = models.CharField(max_length=100, null=True)
    Reporting_Date = models.CharField(max_length=100, null=True)
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE, null=True)
    bank_txn = models.ForeignKey(BankTransaction, on_delete=models.CASCADE, null=True)
    ca_issues = models.ForeignKey(CashAllocationIssues, on_delete=models.CASCADE, null=True)
    ca_corrective = models.ForeignKey(CashAllocationCorrective, on_delete=models.CASCADE, null=True)
    policy_information = models.ForeignKey(PolicyInformation, on_delete=models.CASCADE, null=True)
    ROE = models.DecimalField(decimal_places=6, max_digits=14, null=True)
    ROE_Date = models.DateField(null=True)
    comment = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    created_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, related_name='cashtracker_created_by')
    updated_at = models.DateTimeField(auto_now=True, null=True)
    updated_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, related_name='cashtracker_updated_by')


class WorkflowBankTransactions(models.Model):
    workflow = models.ForeignKey(WorkFlow, on_delete=models.CASCADE, null=True, blank=True)
    workflow_json_data = models.JSONField(blank=True, null=True)
    changefields = models.JSONField(blank=True, null=True)
    current_step = models.CharField(max_length=100, blank=True, null=True)
    bank_txn_id = models.CharField(max_length=100, null=True, blank=True)
    workflow_status = models.CharField(max_length=100, null=True, blank=True)
    file = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class CashAllocationLockedUnlockedHistory(models.Model):
    """
    This model represents the history of locked/unlocked states for CashAllocation records.
    """
    date_range = models.CharField(max_length=255)  # Adjust length if needed for your date range format
    comment = models.TextField(null=True)
    locked = models.BooleanField(default=False)
    unlocked = models.BooleanField(default=False)  # Unlocked by default to simplify logic
    no_of_record = models.IntegerField(null=False)
    locked_unlocked_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True)
    locked_unlocked_date = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return f"CashAllocationLockedUnlockedHistory (date_range: {self.date_range}, locked: {self.locked}, unlocked: {self.unlocked}, locked_unlocked_by: {self.locked_unlocked_by}, locked_unlocked_date: {self.locked_unlocked_date})"


class SchedulerCheck(models.Model):
    """
    This model for schedular check
    """

    lock_type = models.CharField(max_length=50)
    locked = models.BooleanField(default=False)

class AccountingMonthEnd(models.Model):
    accounting_month_date = models.DateField()
    accounting_month_start_date = models.DateField()
    accounting_month_end_date = models.DateField()
    created_by = models.ForeignKey(Users, on_delete=models.SET_NULL, related_name='accounting_month_end_created_by', null=True, blank=True)
    updated_by = models.ForeignKey(Users, on_delete=models.SET_NULL, related_name='accounting_month_end_updated_by', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)


class CashAllocaionAudit(models.Model):
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE, null=True)
    audit_data = models.JSONField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)


class BankTransactionAudit(models.Model):
    bank_transaction = models.ForeignKey(BankTransaction, on_delete=models.CASCADE, null=True)
    audit_data = models.JSONField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)


class FollowUp(models.Model):
    bank_transaction = models.ForeignKey(BankTransaction, on_delete=models.CASCADE, null=True, related_name='followup_bank_txn')
    cash_allocation = models.ForeignKey(CashAllocation, on_delete=models.CASCADE, null=True, related_name='followup_ca')
    query_status = models.CharField(max_length=200)
    date1_value = models.DateField(null=True, blank=True)
    date1 = models.DateTimeField(null=True, blank=True)
    date2_value = models.DateField(null=True, blank=True)
    date2 = models.DateTimeField(null=True, blank=True)
    date3_value = models.DateField(null=True, blank=True)
    date3 = models.DateTimeField(null=True, blank=True)
    escalation_date_value = models.DateField(null=True, blank=True)
    escalation_date = models.DateTimeField(null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey('users.Users', on_delete=models.CASCADE, null=True, blank=True, related_name='followup_created_user')
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_by = models.ForeignKey('users.Users', on_delete=models.CASCADE, null=True, blank=True, related_name='followup_updated_user')
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)


class FollowUpAudit(models.Model):
    follow_up = models.ForeignKey(FollowUp, on_delete=models.CASCADE, null=True)
    audit_data = models.JSONField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)