# Generated by Django 4.2.7 on 2023-11-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userpermissions'),
        ),
    ]
