# Generated by Django 4.2.7 on 2023-11-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
    ]
