# Generated by Django 4.2.7 on 2023-12-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
    ]
