# Generated by Django 4.2.7 on 2024-01-22 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_allocationstatus_bindingagreement_cashtransfer_and_more'),
        ('users', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userpermissions'),
            preserve_default=False,
        ),
    ]
