# Generated by Django 4.2.7 on 2024-01-22 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_department_users_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reporting_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
