# Generated by Django 4.2.7 on 2024-01-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_reporting_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
    ]
