# Generated by Django 4.2.7 on 2024-01-22 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_users_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userpermissions'),
            preserve_default=False,
        ),
    ]
