# Generated by Django 4.2.7 on 2024-01-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='permissions_list',
            field=models.JSONField(),
        ),
    ]
