# Generated by Django 4.2.7 on 2024-02-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userpermissions_permissions_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
