# Generated by Django 4.2.7 on 2024-01-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_Transaction_Id', models.CharField(max_length=100)),
                ('Accounting_Month', models.DateField()),
                ('PT_Receving_Bank_Account_Name_Entity', models.CharField(max_length=100)),
                ('Receiving_Bank_Account', models.CharField(blank=True, max_length=100, null=True)),
                ('Broker_Branch', models.CharField(max_length=100)),
                ('Broker', models.CharField(max_length=100)),
                ('Payment_Receive_Date', models.DateTimeField()),
                ('Payment_Reference', models.CharField(max_length=100)),
                ('Payment_Currency_Code', models.CharField(max_length=100)),
                ('Bank_Currency_Code', models.CharField(max_length=100)),
                ('Bank_Exchange_Rate', models.CharField(max_length=100)),
                ('Bank_Exchange_Charges', models.CharField(max_length=100)),
                ('Bank_Charges', models.CharField(max_length=100)),
                ('Receivable_Amount', models.CharField(max_length=100)),
                ('TL_Fees', models.CharField(max_length=100)),
                ('Currency', models.CharField(max_length=100)),
                ('File_Name', models.FileField(blank=True, null=True, upload_to='bank/media/')),
                ('Created_By', models.CharField(max_length=100)),
                ('Analyst_Name', models.CharField(max_length=100)),
                ('Date_And_Time', models.DateTimeField(max_length=100)),
                ('Uploaded_By', models.CharField(max_length=100)),
            ],
        ),
    ]
