# Generated by Django 4.2.7 on 2024-01-09 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='Assigned_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
