# Generated by Django 4.2.7 on 2024-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0002_banktransaction_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='Allocation_Status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
