# Generated by Django 4.2.7 on 2024-01-17 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankmanagement', '0003_banktransaction_allocation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='Assigned_User',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='Assigned_User',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
