# Generated by Django 4.2.7 on 2024-02-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('documents'),
        ('bankmanagement', '0005_banktransaction_assigned_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_status', models.CharField(max_length=100)),
                ('allocation_systemid', models.CharField(max_length=100)),
                ('policy_id', models.CharField(max_length=100)),
                ('allocation_entity', models.CharField(max_length=100)),
                ('allocation_binder', models.CharField(max_length=100)),
                ('allocation_umr', models.CharField(max_length=100)),
                ('binding_agreement', models.CharField(max_length=100)),
                ('allocation_eea', models.CharField(max_length=100)),
                ('allocation_scm', models.CharField(max_length=100)),
                ('allocation_scmname', models.CharField(max_length=100)),
                ('allocation_invoice_verification', models.CharField(max_length=100)),
                ('receivable_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unallocated_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('XFIbatchno', models.CharField(max_length=100)),
                ('cashreference', models.CharField(max_length=100)),
                ('GXPbatchno', models.CharField(max_length=100)),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('accounting_monthyear', models.IntegerField(default=None)),
                ('allocatedby', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CashAllocationIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('issue_category', models.CharField(max_length=100)),
                ('issue_owner', models.CharField(max_length=100)),
                ('system_id', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=150)),
                ('assignment', models.CharField(max_length=150)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('age_days', models.IntegerField()),
                ('accounting_monthyear', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
                ('cash_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation')),
                ('correction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.correctiontype')),
            ],
        ),
    ]
