# Generated by Django 4.2.7 on 2024-01-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0006_cashallocation_cashallocationissues'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAllocationWriteoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('writeoff_reason', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('writeoff_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comments', models.TextField()),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('aprover_name', models.CharField(max_length=100)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('system_id', models.CharField(max_length=100)),
                ('accounting_monthyear', models.IntegerField()),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
                ('cash_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation')),
            ],
        ),
        migrations.CreateModel(
            name='CashAllocationRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('refund_reason', models.TextField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('refund_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comments', models.TextField()),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('aprover_name', models.CharField(max_length=100)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('system_id', models.CharField(max_length=100)),
                ('accounting_monthyear', models.IntegerField()),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
                ('cash_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation')),
            ],
        ),
        migrations.CreateModel(
            name='CashAllocationCorrective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('transfer_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producing_entity_bankid', models.CharField(max_length=100)),
                ('producing_bank_currid', models.CharField(max_length=100)),
                ('bank_roe', models.CharField(max_length=100)),
                ('payment_currid', models.CharField(max_length=100)),
                ('bank_curr', models.CharField(max_length=100)),
                ('receivable_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unallocated_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accounting_monthyear', models.IntegerField()),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
                ('cash_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation')),
            ],
        ),
    ]
