# Generated by Django 4.2.7 on 2024-02-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0006_cashallocation_cashallocationissues'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='assigned_users_list',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
