# Generated by Django 4.2.7 on 2024-02-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0007_cashallocationwriteoff_cashallocationrefund_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('paid_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('wire_number', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('system_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
                ('accounting_monthyear', models.IntegerField()),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CrossAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('ca_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ca_change', models.CharField(max_length=100)),
                ('ca_impact', models.CharField(max_length=100)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('aprover_name', models.CharField(max_length=100)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('system_id', models.CharField(max_length=100)),
                ('accounting_monthyear', models.IntegerField()),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveTRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('receivable_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('wire_number', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('system_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
                ('accounting_monthyear', models.IntegerField()),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CashAllocationMSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('msd_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('je_number', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('system_date', models.DateTimeField(auto_now_add=True)),
                ('accounting_monthyear', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
            ],
        ),
        migrations.CreateModel(
            name='CashAllocationCFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('cfi_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cfi_change', models.CharField(max_length=100)),
                ('cfi_impact', models.CharField(max_length=100)),
                ('reallocation_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('aprover_name', models.CharField(max_length=100)),
                ('process_date', models.DateTimeField(auto_now_add=True)),
                ('system_id', models.CharField(max_length=100)),
                ('accounting_monthyear', models.IntegerField()),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
            ],
        ),
    ]
