# Generated by Django 4.2.7 on 2024-02-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0008_premiumpayment_crossallocation_correctivetrf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashallocation',
            name='bank_curr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='bank_roe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='cash_reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='payment_currency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
