# Generated by Django 4.2.7 on 2024-02-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0009_cashallocation_bank_curr_cashallocation_bank_roe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashallocationcfi',
            name='cash_allocation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashallocationmsd',
            name='cash_allocation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correctivetrf',
            name='cash_allocation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crossallocation',
            name='cash_allocation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='cash_allocation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.cashallocation'),
            preserve_default=False,
        ),
    ]
