# Generated by Django 4.2.7 on 2024-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0010_cashallocationcfi_cash_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='allocation_date',
            field=models.DateTimeField(),
        ),
    ]
