# Generated by Django 4.2.7 on 2024-02-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0007_banktransaction_assigned_users_list'),
        ('bankmanagement', '0011_alter_cashallocationcorrective_allocation_date'),
    ]

    operations = [
    ]
