# Generated by Django 4.2.7 on 2024-02-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0012_alter_cashallocation_allocation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocation',
            name='GXPbatchno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='XFIbatchno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='accounting_monthyear',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocated_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocatedby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_binder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_eea',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_entity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_invoice_verification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_scm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_scmname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_umr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='bank_curr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='bank_roe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='binding_agreement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='cash_reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='cashreference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='payment_currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='receivable_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='unallocated_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcfi',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcfi',
            name='approved_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcfi',
            name='process_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcfi',
            name='reallocation_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcfi',
            name='system_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='allocated_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='allocation_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='bank_curr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='bank_roe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='payment_currid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='producing_bank_currid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='producing_entity_bankid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='receivable_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='unallocated_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationissues',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationissues',
            name='age_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationissues',
            name='assignment',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationissues',
            name='issue_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationissues',
            name='issue_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationissues',
            name='issue_owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationissues',
            name='system_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationmsd',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationmsd',
            name='process_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationmsd',
            name='system_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationmsd',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationrefund',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationrefund',
            name='approved_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationrefund',
            name='process_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationrefund',
            name='system_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationwriteoff',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationwriteoff',
            name='approved_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationwriteoff',
            name='process_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationwriteoff',
            name='system_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='correctivetrf',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='correctivetrf',
            name='system_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='correctivetrf',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crossallocation',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crossallocation',
            name='approved_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crossallocation',
            name='ca_change',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crossallocation',
            name='ca_impact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crossallocation',
            name='process_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crossallocation',
            name='system_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='accounting_monthyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='allocated_amt',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='payment_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='system_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
