# Generated by Django 4.2.7 on 2024-02-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0012_merge_20240208_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='assigned_users_list',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
