# Generated by Django 4.2.7 on 2024-02-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0013_alter_banktransaction_assigned_users_list'),
        ('bankmanagement', '0014_merge_20240209_0023'),
    ]

    operations = [
    ]
