# Generated by Django 4.2.7 on 2024-02-19 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankmanagement', '0015_merge_20240219_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='allocation_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=200)),
                ('comments', models.TextField()),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uptime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ManyToManyField(blank=True, related_name='workstep_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=200)),
                ('workflow_step', models.ManyToManyField(blank=True, related_name='worksteps', to='bankmanagement.workstep')),
            ],
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.workflow'),
        ),
    ]
