# Generated by Django 4.2.7 on 2024-02-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0016_alter_cashallocationcorrective_allocation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstep',
            name='uptime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
