# Generated by Django 4.2.7 on 2024-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_policyinformation_binding_agreement'),
        ('bankmanagement', '0017_alter_workstep_uptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashallocation',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='cashallocationcfi',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='cashallocationcorrective',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='cashallocationissues',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='cashallocationmsd',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='cashallocationrefund',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='cashallocationwriteoff',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='correctivetrf',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='crossallocation',
            name='policy_id',
        ),
        migrations.RemoveField(
            model_name='premiumpayment',
            name='policy_id',
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationcfi',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='bank_account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='currency_from_bank_stmt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='receiving_entity_bank_account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationissues',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationmsd',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationrefund',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationwriteoff',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='correctivetrf',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='crossallocation',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='policy',
            field=models.ManyToManyField(blank=True, to='documents.policyinformation'),
        ),
    ]
