# Generated by Django 4.2.7 on 2024-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documents_document_details'),
        ('bankmanagement', '0018_remove_cashallocation_policy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='document_files',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.documents'),
        ),
    ]
