# Generated by Django 4.2.7 on 2024-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0018_remove_cashallocation_policy_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accounting_Monthy', models.CharField(max_length=100, null=True)),
                ('Allocation_Status', models.CharField(max_length=100, null=True)),
                ('Division', models.CharField(max_length=100, null=True)),
                ('Receiving_Bank_Account', models.CharField(max_length=100, null=True)),
                ('Cash_Transfers', models.CharField(max_length=100, null=True)),
                ('Policy_Type', models.CharField(max_length=100, null=True)),
                ('LOB', models.CharField(max_length=100, null=True)),
                ('Broker', models.CharField(max_length=100, null=True)),
                ('Broker_Branch', models.CharField(max_length=100, null=True)),
                ('Binding_Agreement', models.CharField(max_length=100, null=True)),
                ('SCM_Partners', models.CharField(max_length=100, null=True)),
                ('EEA_Non_EEA', models.CharField(max_length=100, null=True)),
                ('Payment_Receive_Date', models.CharField(max_length=100, null=True)),
                ('Payment_Currency_Code', models.CharField(max_length=100, null=True)),
                ('ROE_Bank_Statement', models.CharField(max_length=100, null=True)),
                ('Master_Binder', models.CharField(max_length=100, null=True)),
                ('Policy', models.CharField(max_length=100, null=True)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('Bank_Charges', models.CharField(max_length=100, null=True)),
                ('Receivable_Amount', models.CharField(max_length=100, null=True)),
                ('Allocated_Amount', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
