# Generated by Django 4.2.7 on 2024-02-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0019_banktransaction_document_files'),
        ('bankmanagement', '0019_cashtracker'),
    ]

    operations = [
    ]
