# Generated by Django 4.2.7 on 2024-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0020_merge_20240227_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='transfer_pt_bank_account_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationrefund',
            name='currency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationwriteoff',
            name='currency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
