# Generated by Django 4.2.7 on 2024-02-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0021_cashallocationcorrective_transfer_pt_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashallocation',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='cashallocationcfi',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='cashallocationcorrective',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='cashallocationissues',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='cashallocationmsd',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='cashallocationrefund',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='cashallocationwriteoff',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='correctivetrf',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='crossallocation',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='premiumpayment',
            name='policy',
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationcfi',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationissues',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationmsd',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationrefund',
            name='bank_transaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationrefund',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationwriteoff',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='correctivetrf',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crossallocation',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='policy_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
