# Generated by Django 4.2.7 on 2024-03-01 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_documents_document_type'),
        ('bankmanagement', '0022_remove_cashallocation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.bankdetails'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='broker_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.brokerinformation'),
        ),
    ]
