# Generated by Django 4.2.7 on 2024-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0022_remove_cashallocation_policy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='PT_Receving_Bank_Account_Name_Entity',
            new_name='Bank_Account_Name_Entity',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='PT_Receving_Bank_Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
