# Generated by Django 4.2.7 on 2024-03-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_documents_document_type'),
        ('bankmanagement', '0023_banktransaction_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashallocation',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationcfi',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationcfi',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_cfi', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_corrective', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationissues',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationissues',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_issues', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationmsd',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationmsd',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_msd', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationrefund',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationrefund',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_refund', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationwriteoff',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='cashallocationwriteoff',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_writeoff', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='correctivetrf',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='correctivetrf',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_trf', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='crossallocation',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='crossallocation',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_ca', to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='policy_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.policyinformation'),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='policy_mf',
            field=models.ManyToManyField(blank=True, related_name='policy_premium', to='documents.policyinformation'),
        ),
    ]
