# Generated by Django 4.2.7 on 2024-03-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0024_cashallocation_policy_fk_cashallocation_policy_mf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='treasury_confirmed_transfer_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationrefund',
            name='broker_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocationwriteoff',
            name='cash_reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crossallocation',
            name='new_allocation_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
