# Generated by Django 4.2.7 on 2024-03-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0023_rename_pt_receving_bank_account_name_entity_banktransaction_bank_account_name_entity_and_more'),
        ('bankmanagement', '0025_cashallocationcorrective_treasury_confirmed_transfer_date_and_more'),
    ]

    operations = [
    ]
