# Generated by Django 4.2.7 on 2024-03-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0026_merge_20240305_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='updated_fields',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
