# Generated by Django 4.2.7 on 2024-03-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0027_banktransaction_updateddateandtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
