# Generated by Django 4.2.7 on 2024-03-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0028_alter_banktransaction_updated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashallocationcorrective',
            name='PT_bank_acct_Number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
