# Generated by Django 4.2.7 on 2024-03-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0029_cashallocationcorrective_pt_bank_acct_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstep',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
