# Generated by Django 4.2.7 on 2024-03-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0030_alter_workstep_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstep',
            name='uptime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
