# Generated by Django 4.2.7 on 2024-03-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0031_alter_workstep_uptime'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowBankTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_json_data', models.JSONField()),
                ('changefields', models.JSONField()),
                ('current_step', models.CharField(max_length=100, null=True)),
                ('bank_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.banktransaction')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.workflow')),
            ],
        ),
    ]
