# Generated by Django 4.2.7 on 2024-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0032_workflowbanktransactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowbanktransactions',
            name='bank_txn',
        ),
        migrations.AddField(
            model_name='workflowbanktransactions',
            name='bank_txn_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
