# Generated by Django 4.2.7 on 2024-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0033_remove_workflowbanktransactions_bank_txn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowbanktransactions',
            name='bank_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflowbanktransactions',
            name='changefields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowbanktransactions',
            name='current_step',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflowbanktransactions',
            name='workflow_json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
