# Generated by Django 4.2.7 on 2024-03-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0030_cashtrackerreport'),
        ('bankmanagement', '0034_alter_workflowbanktransactions_bank_txn_id_and_more'),
    ]

    operations = [
    ]
