# Generated by Django 4.2.7 on 2024-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0035_merge_20240321_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtracker',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashtracker',
            name='txn_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
