# Generated by Django 4.2.7 on 2024-03-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0035_merge_20240321_1226'),
        ('bankmanagement', '0036_cashtracker_bank_name_cashtracker_txn_id'),
    ]

    operations = [
    ]
