# Generated by Django 4.2.7 on 2024-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0037_merge_20240323_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowbanktransactions',
            name='workflow_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
