# Generated by Django 4.2.7 on 2024-04-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0035_merge_20240320_2306'),
        ('bankmanagement', '0038_workflowbanktransactions_workflow_status'),
    ]

    operations = [
    ]
