# Generated by Django 4.2.7 on 2024-04-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0039_merge_20240402_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_no', models.CharField(max_length=100, null=True)),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('uploaded_date', models.DateField()),
                ('uploaded_time', models.DateTimeField()),
                ('file_date', models.DateField()),
                ('uploaded_status', models.CharField(max_length=100, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('ct_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('ct_amount_car', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('bank_charges', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('ct_bank_charges', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('ct_bank_charges_var', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('category_total', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('error_message', models.CharField(max_length=100, null=True)),
                ('locked', models.CharField(max_length=100, null=True)),
                ('allocated_analyst_id', models.CharField(max_length=100, null=True)),
                ('allocated_date', models.DateField()),
                ('final_status', models.CharField(max_length=100, null=True)),
                ('analyst_comments', models.CharField(max_length=100, null=True)),
                ('resolution_date', models.DateField()),
                ('file_name_hyperlink', models.FileField(blank=True, null=True, upload_to='bank/')),
            ],
        ),
    ]
