# Generated by Django 4.2.7 on 2024-04-05 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankmanagement', '0040_bankreconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreconciliation',
            name='allocated_analyst_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
