# Generated by Django 4.2.7 on 2024-04-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0041_alter_bankreconciliation_allocated_analyst_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='auto_upload',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankmanagement.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='locked',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='txn_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
