# Generated by Django 4.2.7 on 2024-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0042_banktransaction_auto_upload_and_more'),
    ]

    operations = [
        
    ]
