# Generated by Django 4.2.7 on 2024-05-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_allocationstatus_addeddateandtime_and_more'),
        ('bankmanagement', '0042_banktransaction_auto_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.bankdetails'),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='GXBAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='GXB_Variance_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='Installment_Amount_org',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='Installment_Duedate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='Installment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='Settlement_ccy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.currencydetails'),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='XFIAmount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='XFI_Variance_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='historical',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
