# Generated by Django 4.2.7 on 2024-05-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0043_alter_cashallocation_accounting_monthyear'),
        ('bankmanagement', '0043_bankreconciliation_bank_details_and_more'),
    ]

    operations = [
    ]
