# Generated by Django 4.2.7 on 2024-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0044_merge_20240505_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreconciliation',
            name='locked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocation',
            name='accounting_monthyear',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cashallocationwriteoff',
            name='accounting_monthyear',
            field=models.DateField(null=True),
        ),
    ]
