# Generated by Django 4.2.7 on 2024-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0045_alter_bankreconciliation_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='Bank_Exchange_Rate',
            field=models.DecimalField(decimal_places=6, max_digits=14, null=True),
        ),
    ]
