# Generated by Django 4.2.7 on 2024-05-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0046_alter_banktransaction_bank_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='Bank_Exchange_Charges',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
