# Generated by Django 4.2.7 on 2024-05-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0047_alter_banktransaction_bank_exchange_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='Bank_Charges',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
    ]
