# Generated by Django 4.2.7 on 2024-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0049_alter_banktransaction_receivable_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='TL_Fees',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
