# Generated by Django 4.2.7 on 2024-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0050_alter_banktransaction_tl_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='auto_upload',
            field=models.BooleanField(default=True),
        ),
    ]
