# Generated by Django 4.2.7 on 2024-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0051_alter_banktransaction_auto_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='locked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
