# Generated by Django 4.2.7 on 2024-05-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0052_alter_banktransaction_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocation',
            name='allocation_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
