# Generated by Django 4.2.7 on 2024-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0054_alter_cashallocation_bank_roe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationissues',
            name='issue_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
