# Generated by Django 4.2.7 on 2024-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0055_alter_cashallocationissues_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationissues',
            name='accounting_monthyear',
            field=models.DateField(default=None, null=True),
        ),
    ]
