# Generated by Django 4.2.7 on 2024-05-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0056_alter_cashallocationissues_accounting_monthyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='bank_roe',
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
    ]
