# Generated by Django 4.2.7 on 2024-05-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0057_alter_cashallocationcorrective_bank_roe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='accounting_monthyear',
            field=models.DateField(default=None, null=True),
        ),
    ]
