# Generated by Django 4.2.7 on 2024-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0059_alter_cashallocationcorrective_allocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationcorrective',
            name='treasury_confirmed_transfer_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
