# Generated by Django 4.2.7 on 2024-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0060_alter_cashallocationcorrective_treasury_confirmed_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationwriteoff',
            name='request_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
