# Generated by Django 4.2.7 on 2024-05-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0062_alter_cashallocationwriteoff_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationwriteoff',
            name='process_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
