# Generated by Django 4.2.7 on 2024-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0064_alter_cashallocationrefund_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationrefund',
            name='approved_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
