# Generated by Django 4.2.7 on 2024-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0066_alter_cashallocationrefund_process_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationrefund',
            name='accounting_monthyear',
            field=models.DateField(null=True),
        ),
    ]
