# Generated by Django 4.2.7 on 2024-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0068_alter_cashallocationcfi_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationcfi',
            name='reallocation_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
