# Generated by Django 4.2.7 on 2024-05-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0069_alter_cashallocationcfi_reallocation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationcfi',
            name='approved_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
