# Generated by Django 4.2.7 on 2024-05-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0072_alter_cashallocationcfi_accounting_monthyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossallocation',
            name='request_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
