# Generated by Django 4.2.7 on 2024-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0075_alter_crossallocation_process_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossallocation',
            name='accounting_monthyear',
            field=models.DateField(default=None, null=True),
        ),
    ]
