# Generated by Django 4.2.7 on 2024-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0078_alter_cashallocationmsd_process_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationmsd',
            name='system_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
