# Generated by Django 4.2.7 on 2024-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0079_alter_cashallocationmsd_system_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashallocationmsd',
            name='accounting_monthyear',
            field=models.DateField(default=None, null=True),
        ),
    ]
