# Generated by Django 4.2.7 on 2024-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0080_alter_cashallocationmsd_accounting_monthyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpayment',
            name='payment_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
