# Generated by Django 4.2.7 on 2024-05-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0084_alter_correctivetrf_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctivetrf',
            name='system_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
