# Generated by Django 4.2.7 on 2024-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0087_alter_cashtracker_accounting_monthy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtracker',
            name='Payment_Receive_Date',
            field=models.DateField(default=None, null=True),
        ),
    ]
