# Generated by Django 4.2.7 on 2024-05-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0090_alter_cashtracker_bank_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtracker',
            name='Receivable_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
