# Generated by Django 4.2.7 on 2024-05-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0092_alter_cashtracker_allocated_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashallocation',
            old_name='GXBAmount',
            new_name='gxbamount',
        ),
        migrations.RenameField(
            model_name='cashallocation',
            old_name='Installment_Amount_org',
            new_name='installment_amount_org',
        ),
        migrations.RenameField(
            model_name='cashallocation',
            old_name='Installment_Duedate',
            new_name='installment_duedate',
        ),
        migrations.RenameField(
            model_name='cashallocation',
            old_name='Installment_number',
            new_name='installment_number',
        ),
        migrations.RenameField(
            model_name='cashallocation',
            old_name='Settlement_ccy',
            new_name='settlement_ccy',
        ),
        migrations.RenameField(
            model_name='cashallocation',
            old_name='XFIAmount',
            new_name='xfi_amount',
        ),
        migrations.RenameField(
            model_name='cashallocation',
            old_name='XFI_Variance_Amount',
            new_name='xfi_variance_amount',
        ),
    ]
