# Generated by Django 4.2.7 on 2024-05-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankmanagement', '0093_rename_gxbamount_cashallocation_gxbamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashallocation',
            name='locked',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashallocation',
            name='locked_datetime',
            field=models.DateField(null=True),
        ),
    ]
