# Generated by Django 4.2.7 on 2024-05-09 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankmanagement', '0094_remove_cashallocation_gxb_variance_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAllocationLockedUnlockedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('unlocked', models.BooleanField(default=False)),
                ('no_of_record', models.IntegerField()),
                ('locked_unlocked_date', models.DateTimeField(auto_now_add=True)),
                ('locked_unlocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
