# Generated by Django 4.2.7 on 2024-05-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0094_remove_cashallocation_gxb_variance_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashallocation',
            old_name='GXB_Variance_Amount',
            new_name='gxb_variance_amount',
        ),
    ]
