# Generated by Django 4.2.7 on 2024-05-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0095_remove_cashallocation_gxb_variance_amount_and_more'),
        ('bankmanagement', '0095_rename_gxb_variance_amount_cashallocation_gxb_variance_amount'),
    ]

    operations = [
    ]
