# Generated by Django 4.2.7 on 2024-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankmanagement', '0096_merge_20240513_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
