from django.db import models
from documents.models import Documents
from users.models import Users
import datetime


class PremBDXFiles(models.Model):
    filename = models.TextField()
    sheet_name = models.TextField()
    upload_status = models.BooleanField(default=False)
    is_prembdx_generated = models.BooleanField(default=False)
    is_exception_generated = models.BooleanField(default=False)
    entity_name = models.CharField(max_length=255, null=True, blank=True)
    month = models.CharField(max_length=255, null=True, blank=True)
    year = models.CharField(max_length=255, null=True, blank=True)
    version = models.CharField(max_length=255, null=True, blank=True)
    scm_status = models.CharField(max_length=255, null=True, blank=True)
    number_of_records_uploaded = models.CharField(max_length=255, null=True, blank=True)
    final_net_payment = models.CharField(max_length=255, null=True, blank=True)
    commission_amount = models.CharField(max_length=255, null=True, blank=True)
    lob = models.CharField(max_length=255, null=True, blank=True)
    error_message = models.TextField(null=True, blank=True)
    columns_not_found = models.TextField(null=True, blank=True)
    deleted = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)
    upload_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True)


class PremiumBDX(models.Model):
    coverholdname = models.TextField(null=True, blank=True)
    yearofaccount = models.TextField(null=True, blank=True)
    umr = models.TextField(null=True, blank=True)
    agreementno = models.TextField(null=True, blank=True)
    certificateref = models.TextField(null=True, blank=True)
    lob = models.TextField(null=True, blank=True)
    classofbusiness = models.TextField(null=True, blank=True)
    risktransactiontype = models.TextField(null=True, blank=True)
    country = models.TextField(null=True, blank=True)
    category = models.TextField(null=True, blank=True)
    placingbroker = models.TextField(null=True, blank=True)
    insure = models.TextField(null=True, blank=True)
    settlementcurrency = models.TextField(null=True, blank=True)
    originalcurrency = models.TextField(null=True, blank=True)
    commissionper = models.DecimalField(decimal_places=6, max_digits=18, null=True)
    brokpremper = models.DecimalField(decimal_places=6, max_digits=18, null=True)
    percentforlloyds = models.DecimalField(decimal_places=8, max_digits=18, null=True)
    rateofexchange = models.DecimalField(decimal_places=6, max_digits=18, null=True)
    grosspremiumpaidthistime = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    gppsettlement = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    commissionamount = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    commissionamountsettlement = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    fnporiginalcurrency = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    brokerageamountoc = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    finalnetpremiumsc = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    brokerageamountsc = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    totaltaxesandlevies = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    totaltaxesandleviessc = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    accessoriitaly = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    terrorismpremium = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    finalnetpremiumusd = models.DecimalField(decimal_places=2, max_digits=12, null=True)
    filename = models.TextField(null=True, blank=True)
    paymentrequestid = models.CharField(max_length=255, null=True, blank=True)
    sheettab = models.TextField(null=True, blank=True)
    bindingagreement = models.TextField(null=True, blank=True)
    month = models.TextField(null=True, blank=True)
    year = models.TextField(null=True, blank=True)
    processingdate = models.DateField(null=True)
    folder = models.TextField(null=True, blank=True)
    archived = models.BooleanField(default=False)
    document = models.ForeignKey(Documents, on_delete=models.CASCADE, null=True)
    analyst_id = models.ForeignKey(Users, on_delete=models.CASCADE, null=True)
    old_file_name = models.CharField(max_length=255, null=True)
    old_tab_name = models.CharField(max_length=255, null=True)
    migrated_data = models.BooleanField(default=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_datetime = models.DateTimeField(null=True)
    receiving_bank_account_name = models.CharField(max_length=255, null=True, blank=True)
    receiving_bank_account = models.CharField(max_length=255, null=True, blank=True)
    transfer_to_pt_bank_account_name = models.CharField(max_length=255, null=True, blank=True)
    treasury_transfer_date = models.CharField(max_length=255, null=True, blank=True)
    invoice_bank_account = models.CharField(max_length=255, null=True, blank=True)
    final_bank_account = models.CharField(max_length=255, null=True, blank=True)
    final_bank_name = models.CharField(max_length=255, null=True, blank=True)
    rebate = models.CharField(max_length=255, null=True, blank=True)
    net_payment = models.CharField(max_length=255, null=True, blank=True)
    gross_prem_sett_arch = models.CharField(max_length=255, null=True, blank=True)
    net_prem_sett_incld_rebate_arch = models.CharField(max_length=255, null=True, blank=True)
    payment_id = models.CharField(max_length=255, null=True, blank=True)
    to_account_name = models.CharField(max_length=255, null=True, blank=True)
    bank_account_number = models.CharField(max_length=255, null=True, blank=True)
    commission_transfer_from_bank_acc_name = models.CharField(max_length=255, null=True, blank=True)
    commission_transfer_from_bank_acc_number = models.CharField(max_length=255, null=True, blank=True)
    commission_bank_transfer_account_number = models.CharField(max_length=255, null=True, blank=True)
    commission_bank_transfer_name = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.filename)


class PaymentTreasury(models.Model):
    Category = models.CharField(null=True)
    Type_of_Payment = models.CharField(null=True)
    Payment_to = models.CharField(null=True)
    Source_Input = models.CharField(null=True)
    File_Name = models.CharField(null=True)
    BDX_Name_Month_and_Year = models.CharField(null=True)
    BDX_Month_and_Year_only_2024 = models.CharField(null=True)
    Coverholder_Name = models.CharField(null=True)
    Coverholder_Entity = models.CharField(null=True)
    Payment_Type = models.CharField(null=True)
    Certificate_Ref = models.CharField(null=True)
    LOB = models.CharField(null=True)
    UMR = models.CharField(null=True)
    Sett_Currency = models.CharField(null=True)
    MGA_commision = models.CharField(null=True)
    Net_Premium_to_London = models.FloatField(null=True)
    Adjustment_or_Rebate = models.CharField(null=True)
    Net_Transfer = models.CharField(null=True)
    USD_Value = models.FloatField(null=True)
    Bank_Account = models.CharField(null=True)
    Bank_Reference = models.CharField(null=True)
    Payment_Date = models.DateField(null=True)
    Year = models.CharField(null=True)
    Month = models.CharField(null=True)
    BDX_Location_Link = models.CharField(null=True)
    User_allocated = models.CharField(null=True)
    Comments = models.CharField(null=True)
    BDX_Name_Original = models.CharField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.Category)


class PaymentTreasuryPYMT(models.Model):
    category = models.CharField(null=True)
    type_of_payment = models.CharField(null=True)
    payment_to = models.CharField(null=True)
    source_input = models.CharField(null=True)
    file_name = models.CharField(null=True)
    bdx_name_month_and_year = models.CharField(null=True)
    bdx_month_and_year_only_2024 = models.CharField(null=True)
    coverholder_name = models.CharField(null=True)
    coverholder_entity = models.CharField(null=True)
    payment_type = models.CharField(null=True)
    certificate_ref = models.CharField(null=True)
    lob = models.CharField(null=True)
    umr = models.CharField(null=True)
    sett_currency = models.CharField(null=True)
    mga_commision = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    net_premium_to_london = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    adjustment_or_rebate = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    net_transfer = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    usd_value = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    bank_account = models.CharField(null=True)
    bank_reference = models.CharField(null=True)
    payment_date = models.DateField(null=True)
    year = models.CharField(null=True)
    month = models.CharField(null=True)
    bdx_location_link = models.CharField(null=True)
    user_allocated = models.CharField(null=True)
    comments = models.CharField(null=True)
    bdx_name_original = models.CharField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True)
    payment_id = models.CharField(max_length=20, null=True)
    payment_status = models.CharField(max_length=20, null=True)

    def __str__(self):
        return str(self.category)


class PaymentFile(models.Model):
    Certificate_Ref = models.TextField(null=True)
    BDX_File_name = models.TextField(null=True)
    YOA = models.TextField(null=True)
    Yr_Month = models.TextField(null=True)
    CT_Status = models.TextField(null=True)
    Allocation_Date = models.TextField(null=True)
    Settlement_Currency = models.TextField(null=True)
    BDx_Gross_Premium = models.TextField(null=True)
    BDx_Brokerage = models.TextField(null=True)
    Tax = models.TextField(null=True)
    Net_of_Brokerage = models.TextField(null=True)
    Percentage_for_Lloyd = models.TextField(null=True)
    Lloyds_Market = models.TextField(null=True)
    Receivable_Amount = models.TextField(null=True)
    Net_Premium = models.TextField(null=True)
    CT_Allocation_Amt = models.TextField(null=True)
    Bank_Charges = models.TextField(null=True)
    Variance_with_CT = models.TextField(null=True)
    Overall_Status = models.TextField(null=True)
    CT_Reconiliation_to_BDX_Comments = models.TextField(null=True)
    Treasury_Policy_Level_Payment_Verification = models.TextField(null=True)
    Amount_Match1 = models.TextField(null=True)
    Cash_BDx_Amt = models.TextField(null=True)
    Non_Cash_BDx_Amt = models.TextField(null=True)
    Potential_Payment_Indicator = models.TextField(null=True)
    Comments_Audit = models.TextField(null=True)
    Cash_Bank_Ref = models.TextField(null=True)
    Cash_Payment_Date = models.TextField(null=True)
    Sixteen_Hundred_Nine_Bank_Ref = models.TextField(null=True)
    Sixteen_Hundred_Nine_Payment_Date = models.TextField(null=True)
    Commision = models.TextField(null=True)
    Commision_Bank_Ref = models.TextField(null=True)
    Commision_Payment_Date = models.TextField(null=True)
    Comment = models.TextField(null=True)
    created_date = models.DateField(default=datetime.datetime.now().date(), null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.Certificate_Ref)


class PaymentException(models.Model):
    certificate_ref = models.TextField(null=True)
    bdx_file_name = models.TextField(null=True)
    yoa = models.TextField(null=True)
    yr_month = models.TextField(null=True)
    ct_status = models.TextField(null=True)
    allocation_date = models.DateTimeField(null=True)
    settlement_currency = models.TextField(null=True)
    bdx_gross_premium = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    bdx_brokerage = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    tax = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    net_of_brokerage = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    percentage_for_lloyd = models.DecimalField(decimal_places=4, max_digits=14, null=True)
    lloyds_market = models.DecimalField(decimal_places=4, max_digits=14, null=True)
    receivable_amount = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    net_premium = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    ct_allocation_amt = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    bank_charges = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    variance_with_ct = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    overall_status = models.TextField(null=True)
    ct_reconiliation_to_bdx_comments = models.TextField(null=True)
    treasury_policy_level_payment_verification = models.TextField(null=True)
    amount_match1 = models.TextField(null=True)
    cash_bdx_amt = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    non_cash_bdx_amt = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    potential_payment_indicator = models.TextField(null=True)
    comments_audit = models.TextField(null=True)
    cash_bank_ref = models.TextField(null=True)
    cash_payment_date = models.DateField(null=True)
    sixteen_hundred_nine_bank_ref = models.TextField(null=True)
    sixteen_hundred_nine_payment_date = models.TextField(null=True)
    commission = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    commission_bank_ref = models.TextField(null=True)
    commission_payment_date = models.DateField(null=True)
    comment = models.TextField(null=True)
    version = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    updated_by = models.ForeignKey(Users, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.certificate_ref)


class PaymentDatasheet(models.Model):
    bdx = models.ForeignKey(PremiumBDX, on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.DecimalField(decimal_places=2, max_digits=16, default=0.0, null=True)
    rateofexchange = models.DecimalField(decimal_places=6, max_digits=18, default=0.0, null=True)
    bdx_month = models.TextField(null=True)
    bdx_year = models.TextField(null=True)
    line_of_business = models.TextField(null=True)
    producing_coverholder = models.CharField(max_length=100, null=True)
    receiving_bank_account_name = models.CharField(max_length=100, null=True)
    receiving_bank_account = models.CharField(max_length=100, null=True)
    transfer_to_pt_bank_account_name = models.CharField(max_length=100, null=True)
    treasury_transfer_date = models.DateField(null=True)
    invoice_bank_account = models.CharField(max_length=100, null=True)
    final_bank_account = models.CharField(max_length=100, null=True)
    final_bank_name = models.CharField(max_length=100, null=True)
    SCM_NonSCM = models.TextField(null=True)
    Placing_Broker = models.TextField(null=True)
    rebate = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    net_payment = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    gross_prem_sett_arch = models.TextField(null=True)
    net_prem_sett_incld_rebate_arch = models.TextField(null=True)
    category = models.TextField(null=True)
    payment_id = models.CharField(max_length=20, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class PayoutSummary(models.Model):
    placing_broker = models.TextField(null=True, blank=True)
    scm_non_scm = models.TextField(null=True, blank=True)
    category = models.TextField(null=True, blank=True)
    partner_name = models.TextField(null=True, blank=True)
    overall_status = models.TextField(null=True, blank=True)
    certificate_ref = models.TextField(null=True)
    bdx_file_name = models.TextField(null=True)
    coverholder_name = models.TextField(null=True)
    final_bank_account = models.TextField(null=True)
    final_bank_name = models.TextField(null=True)
    to_bank_account_name = models.TextField(null=True)
    to_bank_account = models.TextField(null=True)
    settlement_currency = models.TextField(null=True)
    sum_of_final_net_premium_settlement_currency = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    sum_of_rebate = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    sum_of_net_payment = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    payment_id = models.CharField(max_length=20, null=True)
    payment_type = models.TextField(null=True)
    bdx_ids = models.TextField(null=True)
    payment_status = models.BooleanField(default=False, null=True)
    payment_complete_status = models.CharField(max_length=100, null=True)
    payment_date = models.DateField(null=True)
    wire_ref = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)


class Coversheet(models.Model):
    certificate_ref = models.TextField(null=True)
    coverholder_name = models.TextField(null=True)
    final_bank_account = models.TextField(null=True)
    final_bank_name = models.TextField(null=True)
    to_bank_account_name = models.TextField(null=True)
    to_bank_account = models.TextField(null=True)
    settlement_currency = models.TextField(null=True)
    sum_of_final_net_premium_settlement_currency = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    sum_of_rebate = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    sum_of_net_payment = models.DecimalField(decimal_places=2, max_digits=14, null=True)
    payment_id = models.CharField(max_length=20, null=True)
    payment_type = models.TextField(null=True)
    payment_status = models.BooleanField(default=False, null=True)
    payment_date = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)    