# Generated by Django 4.2.7 on 2023-12-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(max_length=50)),
            ],
        ),
    ]
