# Generated by Django 4.2.7 on 2023-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/media/'),
        ),
    ]
