# Generated by Django 4.2.7 on 2023-12-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documents_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('duplicate_count', models.CharField(max_length=100)),
                ('soa_received_from_broker', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('broker_branch_location', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
