# Generated by Django 4.2.7 on 2024-01-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_brokerinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('entity_number', models.CharField(max_length=100)),
                ('msd_entity_number', models.CharField(max_length=100)),
                ('entity_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_opening_date', models.DateField(blank=True, null=True)),
                ('account_type', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('msd_acct_number', models.CharField(max_length=100)),
                ('msd_acct_name', models.CharField(max_length=200)),
            ],
        ),
    ]
