# Generated by Django 4.2.7 on 2024-01-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=100)),
                ('country_and_currency', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
    ]
