# Generated by Django 4.2.7 on 2024-01-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('documents', '0005_currencydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BindingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_aggrement_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_transfer_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(max_length=100)),
                ('correction_description', models.TextField(blank=True, null=True)),
                ('allocation_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_divisions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob_code', models.CharField(max_length=100)),
                ('lob', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_start_letter', models.CharField(max_length=100)),
                ('policy_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SCMPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=150)),
            ],
        ),
    ]
