# Generated by Django 4.2.7 on 2024-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_policyinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyinformation',
            name='SCM_Insurer_partner_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
