# Generated by Django 4.2.7 on 2024-02-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_policyinformation_scm_insurer_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyinformation',
            name='Binding_Agreement',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
