# Generated by Django 4.2.7 on 2024-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_policyinformation_binding_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCatergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_catergory', models.CharField(max_length=100)),
            ],
        ),
    ]
