# Generated by Django 4.2.7 on 2024-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_issuecatergory'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
