# Generated by Django 4.2.7 on 2024-02-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documents_document_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(max_length=200),
        ),
    ]
