# Generated by Django 4.2.7 on 2024-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_documents_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=100)),
                ('exchange_rate', models.CharField(max_length=100)),
            ],
        ),
    ]
