# Generated by Django 4.2.7 on 2024-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_bankexchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lob',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lob',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lob',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lob',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lob',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
