# Generated by Django 4.2.7 on 2024-03-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_lob_addeddateandtime_lob_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationstatus',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocationstatus',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allocationstatus',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocationstatus',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allocationstatus',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankexchangerate',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankexchangerate',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankexchangerate',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankexchangerate',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankexchangerate',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bindingagreement',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bindingagreement',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bindingagreement',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bindingagreement',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bindingagreement',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerinformation',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerinformation',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brokerinformation',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerinformation',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brokerinformation',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiontype',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiontype',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='correctiontype',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiontype',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='correctiontype',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencydetails',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencydetails',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currencydetails',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencydetails',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currencydetails',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuecatergory',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuecatergory',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issuecatergory',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuecatergory',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issuecatergory',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policytype',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policytype',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policytype',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policytype',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policytype',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scmpartners',
            name='addedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scmpartners',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scmpartners',
            name='updatedDateAndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scmpartners',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scmpartners',
            name='updated_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
