# Generated by Django 4.2.7 on 2024-05-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_allocationstatus_addeddateandtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Inception_Date',
            field=models.DateField(default=None, null=True),
        ),
    ]
