# Generated by Django 4.2.7 on 2024-05-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_policyinformation_inception_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Expired_Date',
            field=models.DateField(default=None, null=True),
        ),
    ]
