# Generated by Django 4.2.7 on 2024-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_policyinformation_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Signed_Line_Pct',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
