# Generated by Django 4.2.7 on 2024-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_policyinformation_broker_order_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Signed_Order_Pct',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
