# Generated by Django 4.2.7 on 2024-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_alter_policyinformation_signed_order_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Broker_Commision_Pct',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
