# Generated by Django 4.2.7 on 2024-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_policyinformation_coverholder_commision_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Summary_ROE',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
