# Generated by Django 4.2.7 on 2024-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_alter_policyinformation_summary_roe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Settlement_ROE',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
