# Generated by Django 4.2.7 on 2024-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_alter_policyinformation_settlement_roe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Gross_Written_Premium_100_in_Sett',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
