# Generated by Django 4.2.7 on 2024-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_alter_policyinformation_gross_written_premium_100_in_sett'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Net_Written_Premium_100_in_Sett',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
