# Generated by Django 4.2.7 on 2024-05-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_alter_policyinformation_true_net_written_premium_100_in_sett'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Original_ROE',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
