# Generated by Django 4.2.7 on 2024-05-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_alter_policyinformation_original_roe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyinformation',
            name='Gross_Written_Premium_100_in_Sett',
        ),
    ]
