# Generated by Django 4.2.7 on 2024-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_policyinformation_gross_written_premium_100_in_sett_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Gross_Written_Premium_100_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
