# Generated by Django 4.2.7 on 2024-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_alter_policyinformation_gross_written_premium_syndicate_share_in_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Gross_Written_Premium_Non_Syndicate_Share_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
