# Generated by Django 4.2.7 on 2024-05-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_alter_policyinformation_net_written_premium_100_in_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Net_Written_Premium_Agency_Share_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
