# Generated by Django 4.2.7 on 2024-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_alter_policyinformation_net_written_premium_agency_share_in_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinformation',
            name='Diff_in_USD',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Gross_Written_Premium_100_in_USD',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Installment_Agency_Amount_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Installment_Agency_Amount_in_Sett',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Installment_Agency_Amount_in_USD',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Installment_Amount_Syndicate_Share_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Installment_Amount_Syndicate_Share_in_Sett',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Installment_Amount_Syndicate_Share_in_USD',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Net_Written_Premium_100_in_USD',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Net_Written_Premium_Non_Syndicate_Share_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Net_Written_Premium_Syndicate_Share_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Overdue_Days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='Paid_Amount_in_USD',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='True_Net_Written_Premium_100_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='True_Net_Written_Premium_100_in_USD',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='True_Net_Written_Premium_Agency_Share_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='True_Net_Written_Premium_Non_Syndicate_Share_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='policyinformation',
            name='True_Net_Written_Premium_Syndicate_Share_in_Orig',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
