# Generated by Django 4.2.7 on 2024-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_alter_policyinformation_diff_in_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankexchangerate',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
